### ISSUE TITLE
specific Ubuntu version

### ISSUE THREAD

**Issue by laserlab** [ubsuny/ShallowWater-CP2P2024#1]
https://github.com/ubsuny/ShallowWater-CP2P2024/blob/b4100bba4b430b300ebdb2274c83b41c5475daff/.devcontainer/Dockerfile#L2

If there is any specific reason for this ubuntu base image please document. Otherwise I would suggest a more current one.

**Comment by Mosaddeq107** [comment]
Thank you.
Ubuntu:20.04 is the least required version for PETSc, so I specified that. But, I updated the Ubuntu version to 'latest' now.
